X_test <- read.table("./UCI HAR Dataset/test/X_test.txt")
Y_test <- read.table("./UCI HAR Dataset/test/Y_test.txt")
subject_test <- read.table("./UCI HAR Dataset/test/subject_test.txt")
X_train <- read.table("./UCI HAR Dataset/train/X_train.txt")
Y_train <- read.table("./UCI HAR Dataset/train/Y_train.txt")
subject_train <- read.table("./UCI HAR Dataset/train/subject_train.txt")
feature_names <- read.table("./UCI HAR Dataset/features.txt")
activity_labels <- read.table("./UCI HAR Dataset/activity_labels.txt")
library(dplyr)
Y_test_rename <- rename(Y_test, Ycolumn = V1)
Y_train_rename <- rename(Y_train, Ycolumn = V1)
subject_test_rename <- rename(subject_test, subjectcolumn = V1)
subject_train_rename <- rename(subject_train, subjectcolumn = V1)
names(X_test) <- feature_names[["V2"]]
names(X_train) <- feature_names[["V2"]]
X_test_rename <- data.frame(X_test, check.names=TRUE)
X_train_rename <- data.frame(X_train, check.names=TRUE)
combined_test <- cbind(subject_test_rename,Y_test_rename,X_test_rename)
combined_train <- cbind(subject_train_rename,Y_train_rename,X_train_rename)
combined_test_withsource <- mutate(combined_test,sourcecol = "test")
combined_train_withsource <- mutate(combined_train,sourcecol = "train")
combined_all <- rbind(combined_test_withsource,combined_train_withsource)
combined_mean_or_std <- select(combined_all, subjectcolumn, Ycolumn, contains("std"), contains("mean"))
combo_with_activities <- merge(combined_mean_or_std,activity_lables, by.x = "Ycolumn", by.y = "V1")
combo_with_activities2 <- rename(combo_with_activities, activity = V2)
grouped_combo <- group_by(combo_with_activities2,subjectcolumn,activity))
sumall <- summarise_each(grouped_combo, funs(mean))
