X_test <- read.table("./UCI HAR Dataset/test/X_test.txt")
Y_test <- read.table("./UCI HAR Dataset/test/Y_test.txt")
subject_test <- read.table("./UCI HAR Dataset/test/subject_test.txt")
X_train <- read.table("./UCI HAR Dataset/train/X_train.txt")
Y_train <- read.table("./UCI HAR Dataset/train/Y_train.txt")
subject_train <- read.table("./UCI HAR Dataset/train/subject_train.txt")
library(dplyr)
Y_test_rename <- rename(Y_test, Ycolumn = V1)
Y_train_rename <- rename(Y_train, Ycolumn = V1)
subject_test_rename <- rename(subject_test, subjectcolumn = V1)
subject_train_rename <- rename(subject_train, subjectcolumn = V1)
combined_test <- cbind(subject_test_rename,Y_test_rename,X_test)
combined_train <- cbind(subject_train_rename,Y_train_rename,X_train)
combined_test_withsource <- mutate(combined_test,sourcecol = "test")
combined_train_withsource <- mutate(combined_train,sourcecol = "test")
combined_all <- rbind(combined_test_withsource,combined_train_withsource)
